site_name: Magicweb Documentation
site_url: https://magicweb-docs.web.app
repo_url: https://github.com/mordy-python/magicweb/
repo_name: Github
theme:
  name: material
  palette: 
    # scheme: slate
    primary: blue grey
    accent: cyan
nav:
  - Home: index.md
  - Getting Started:
    - Get Started: getting-started/index.md
    - Installation: getting-started/installation.md
    - Create A Basic App: getting-started/basicapp.md